version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql